GET http://localhost:8000/persons
###

GET http://localhost:8000/persons/f7e5094d
###

POST http://localhost:8000/persons
content-type: application/json

{
    "citizen_id": "f7e5094d",
    "prefix": "",
    "give_name":"Adele",
    "family_name":"Bowman",
    "mobile_phone":"",
    "email":"tapigu@lid.edu"
}
###

POST http://localhost:8000/persons
content-type: application/json

{
    "citizen_id": "3a51b357",
    "prefix": "",
    "give_name":"Dean",
    "family_name":"Hodges",
    "mobile_phone":"",
    "email":"rof@vaf.fk"
}
###

PUT http://localhost:8000/persons/3a51b357
content-type: application/json

{
    "prefix": "Mr.",
    "give_name":"Dean",
    "family_name":"Hodges",
    "mobile_phone":"06600666",
    "email":"rof@vaf.fk"
}
###

DELETE http://localhost:8000/courses/3a51b357