GET http://localhost:8000/registers
###

POST http://localhost:8000/registers
content-type: application/json

{
    "type_round":"B001",
    "citizen_id": "f7e5094d",
    "is_paid": "false",
    "is_sponsor":"true"
}
###

POST http://localhost:8000/registers
content-type: application/json

{
    "type_round":"B001",
    "citizen_id": "3a51b357",
    "is_paid": "true",
    "is_sponsor":"false"
}
###

PATCH http://localhost:8000/registers/B001/3a51b357
content-type: application/json

{
    "is_paid": "false",
    "is_sponsor":"false"
}
###

DELETE http://localhost:8000/registers/B001/3a51b357