GET http://localhost:8000/users
###

POST http://localhost:8000/users
content-type: application/json

{
    "username":"admin",
    "password": "123456789",
    "name": "faDorothy Marshalllse",
    "is_admin":"true"
}
###

POST http://localhost:8000/users
content-type: application/json

{
    "username":"staff",
    "password": "123456789",
    "name": "Aaron Bailey",
    "is_admin":"false"
}
###

DELETE http://localhost:8000/users/2